#!/usr/bin/env bash
# Build bun fully-static musl with OpenTUI linked in + dlopen interposition.
# Runs inside the bun-musl-build-env container (host bun for scripts, LLVM 21,
# pinned nightly rust, alpine musl sysroot). Upstream repos are NOT modified:
# the changes live in this repo's patches/ and are applied idempotently.
set -euo pipefail
source "$(dirname "$0")/env.sh"

[ -f "$OPENTUI_OUT/libopentui.a" ] || "$ROOT/scripts/build-opentui.sh"

BIN="$BUN_REPO/build/release-musl-static/bun"

# --- 0.5 oc build-id marker ---
# CI computes OC_BUILD_ID after the sync step resolves the upstream SHAs
# (build.yml, step "Compute oc build id"); local runs fall back to the
# workspace's own refs. The marker is compiled into oc-version.o and linked
# into the executable (see patches/bun-flags-dlopen.patch), so every artifact
# self-identifies its exact oc release — readable via `strings`/`readelf -s`,
# and dlsym-able at runtime through the dl-symtab interposer.
OC_BUILD_ID_SET=0
if [ -n "${OC_BUILD_ID:-}" ]; then
    OC_BUILD_ID_SET=1
else
    fallback_oc="$(read_ref opencode ref 2>/dev/null || echo unknown)"
    fallback_tui="$(read_ref opentui ref 2>/dev/null || echo unknown)"
    fallback_patch="$(sha256sum "$ROOT"/patches/*.patch 2>/dev/null | sha256sum | cut -c1-12)"
    fallback_bun="$(git -C "$BUN_REPO" rev-parse HEAD 2>/dev/null || echo unknown)"
    OC_BUILD_ID="oc-build:tag=oc-local-$(date -u +%Y%m%d) opencode=${fallback_oc}/${fallback_bun} opentui=${fallback_tui} patches=${fallback_patch}"
fi
mkdir -p "$OUT"
cat > "$OUT/oc-version.c" <<EOF
/* generated by build-bun.sh — oc release build-id marker */
__attribute__((used, retain, section(".oc_build_id")))
const char oc_build_id[] = "$OC_BUILD_ID";
EOF
ZIG_CC="$OUT/zig-${ZIG_VERSION:-0.15.2}/zig"
if [ -x "$ZIG_CC" ]; then
    "$ZIG_CC" cc -target x86_64-linux-musl -c "$OUT/oc-version.c" -o "$OPENTUI_OUT/oc-version.o"
else
    cc -c "$OUT/oc-version.c" -o "$OPENTUI_OUT/oc-version.o"
fi
log "build id: $OC_BUILD_ID"

# --- 0. artifact reuse. The CI cache key encodes <bun ref>-<opentui ref>,
#      and the patches live in this repo (pinned refs → pinned patches), so a
#      present artifact with the dl-symtab symbols is exactly the product of
#      this build's inputs. The build-id marker must also match: a cache hit
#      from a previous day carries a stale marker, and only the link step
#      changes (oc-version.o), so a mismatch relinks incrementally instead of
#      rebuilding. FORCE_REBUILD=1 bypasses.
bun_valid() {
    [ "${FORCE_REBUILD:-0}" = "1" ] && return 1
    [ -x "$BIN" ] || return 1
    file "$BIN" 2>/dev/null | grep -q "statically linked" || return 1
    [ "$(nm "$BIN" 2>/dev/null | grep -cE ' T (render|setLogCallback|createEventSink)$' || true)" -gt 0 ] || return 1
    if [ "$OC_BUILD_ID_SET" = "1" ]; then
        strings "$BIN" 2>/dev/null | grep -qF "$OC_BUILD_ID" || return 1
    else
        strings "$BIN" 2>/dev/null | grep -q "oc-build:" || return 1
    fi
}
if bun_valid; then
    log "bun artifact already valid — skipping build (FORCE_REBUILD=1 to rebuild)"
    echo "--- sizes:"; ls -la "$BIN"
    exit 0
fi

# --- 1. build container up ---
ensure_running "$BUN_CONTAINER" "$BUN_IMAGE" \
    -v "$BUN_REPO":/src/bun \
    -w /src/bun \
    -e CARGO_BUILD_JOBS=2 \
    -e PATH=/usr/local/cargo/bin:/usr/lib/llvm-21/bin:/usr/local/bin:/usr/bin:/bin

# revision is baked into the binary (build_options.rs); git must work in the container
docker exec "$BUN_CONTAINER" sh -c 'git config --global --add safe.directory /src/bun; git -C /src/bun rev-parse --short HEAD'

# --- 2. stage opentui artifacts at the hardcoded /opt/static paths (flags.ts patch) ---
docker exec "$BUN_CONTAINER" sh -c 'rm -rf /opt/static/opentui && mkdir -p /opt/static/opentui'
docker cp "$OPENTUI_OUT/libopentui.a"       "$BUN_CONTAINER:/opt/static/opentui/libopentui.a"
docker cp "$OPENTUI_OUT/libyoga_cxx.a"      "$BUN_CONTAINER:/opt/static/opentui/libyoga_cxx.a"
docker cp "$OPENTUI_OUT/dl-symtab.o"        "$BUN_CONTAINER:/opt/static/opentui/dl-symtab.o"
docker cp "$OPENTUI_OUT/oc-version.o"       "$BUN_CONTAINER:/opt/static/opentui/oc-version.o"
docker cp "$OPENTUI_OUT/undefined.rsp" "$BUN_CONTAINER:/opt/static/opentui/undefined.rsp"

# --- 3. apply patches (idempotent) ---
apply_patch "$BUN_REPO" "$ROOT/patches/bun-flags-static.patch" 'flag: ["-static"]'
apply_patch "$BUN_REPO" "$ROOT/patches/bun-flags-dlopen.patch" '--whole-archive,/opt/static/opentui'

# --- 4. build (incremental — only link + strip change) ---
# Low concurrency on purpose: 7.8GB host RAM; -j4 + 2 cargo jobs thrashed
# swap and crashed WSL. -j2 ninja, 1 cargo job, output streamed live.
mkdir -p "$OUT/logs"
log "building (profile=release, linux x64 musl)..."
if ! docker exec -e CARGO_BUILD_JOBS=1 "$BUN_CONTAINER" bash -c \
    'bun ./scripts/build.ts --profile=release --os=linux --arch=x64 --abi=musl \
       --build-dir=build/release-musl-static -j2' 2>&1 | tee "$OUT/logs/bun-build.log"; then
    err "build failed — tail:"; tail -50 "$OUT/logs/bun-build.log"; exit 1
fi
log "build OK (log: $OUT/logs/bun-build.log)"

# --- 5. verify ---
PROFILE_BIN="$BUN_REPO/build/release-musl-static/bun-profile"
file "$BIN"
echo "--- ldd:"; ldd "$BIN" 2>&1 || true
echo "--- .symtab kept? (must be >0):"
SYMCOUNT=$(nm "$BIN" 2>/dev/null | grep -cE " T (render|setLogCallback|createEventSink)$" || true)
echo "$SYMCOUNT"
if [ "$SYMCOUNT" -eq 0 ]; then
    err "dl-symtab symbols missing — the flags.ts patches did not take effect"
    err "check the apply_patch markers (cached build/ can shadow them) and re-run"
    exit 1
fi
echo "--- sizes:"; ls -la "$BIN" "$PROFILE_BIN" 2>/dev/null || true
